export { apiClient } from './client';
export {
  createAuthSession,
  deleteAuthSession,
  getAuthCsrf,
  getAuthSession,
  getVersion,
  registerAccount,
  requestEmailVerification,
  requestPasswordReset,
  resetPassword,
  verifyEmail,
} from './generated/sdk.gen';
export type {
  AuthenticatedSessionDataDto,
  CsrfTokenResponseDto,
  EmailVerificationRequestAcceptedResponseDto,
  EmailVerificationRequestDto,
  LoginRequestDtoWritable,
  LoginResponseDto,
  PasswordResetRequestAcceptedResponseDto,
  PasswordResetRequestDto,
  RegisterAccountRequestDtoWritable,
  RegistrationAcceptedResponseDto,
  ResetPasswordRequestDto,
  SessionStateResponseDto,
  VerifyEmailRequestDtoWritable,
  VerifyEmailResponseDto,
  VersionResponseDto,
} from './generated/types.gen';
