export { apiClient } from './client';
export {
  completeCurrentUserOnboarding,
  createAuthSession,
  deleteAuthSession,
  getAuthCsrf,
  getAuthSession,
  getCurrentUser,
  getVersion,
  initiateAccountDeletion,
  reauthenticate,
  registerAccount,
  requestEmailVerification,
  requestPasswordReset,
  resetPassword,
  updateCurrentUser,
  verifyEmail,
} from './generated/sdk.gen';
export type {
  AccountDeletionProcessResponseDto,
  AccountDeletionRequestDto,
  AuthenticatedSessionDataDto,
  CompleteCurrentUserOnboardingResponse,
  CsrfTokenResponseDto,
  CurrentUserProfileResponseDto,
  EmailVerificationRequestAcceptedResponseDto,
  EmailVerificationRequestDto,
  LoginRequestDtoWritable,
  LoginResponseDto,
  PasswordResetRequestAcceptedResponseDto,
  PasswordResetRequestDto,
  ReauthenticationRequestDtoWritable,
  ReauthenticationResponseDto,
  RegisterAccountRequestDtoWritable,
  RegistrationAcceptedResponseDto,
  ResetPasswordRequestDto,
  SessionStateResponseDto,
  VerifyEmailRequestDtoWritable,
  VerifyEmailResponseDto,
  VersionResponseDto,
} from './generated/types.gen';
